### ISSUE TITLE
how to install and test

### ISSUE THREAD

**Issue by sfahadshahzad** [MagmaPlayout/mp-installer#2]
Please let me know how to install the whole software.

Fahad

**Comment by FernandoJBCosta** [comment]
Hello, can you please help with the installation guide i'm using ubuntu server 14.04lts VMS and i'm geting errors with the install script.

Thanks

**Comment by Rombusevil** [comment]
I leave a link to the docs here: https://github.com/MagmaPlayout/mp-installer/tree/master/docs
